/* gen-tables.c: lowp-tables.h, from MPFR through the kit (kit_ref1).

     gen-tables > lowp-tables.h

   For each one-argument function (lowp-list.h, which must match the kit's
   kit_fns1 name for name), each rounding mode and each input:
     LOWP_T[f][0][mode][x]  the E5M2 result
     LOWP_T[f][1][mode][x]  the E4M3 result, saturating
     LOWP_OVF[f][mode][x/8] bit x%8: the E4M3 result overflowed away from
                            zero, so it is NaN unless saturating
   The output depends on nothing but MPFR's results: no dates, no paths. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "kit.h"

static const char *NAMES[] = {
#define LOWP_F1(f) #f,
#define LOWP_F2(f)
#include "lowp-list.h"
};
enum { NF = sizeof NAMES / sizeof *NAMES };
static const mpfr_rnd_t RND[4] = {MPFR_RNDN, MPFR_RNDU, MPFR_RNDD, MPFR_RNDZ};
static unsigned char T[NF][2][4][256], OVF[NF][4][32];

int main(void)
{
  if (NF != kit_nfns1) { fprintf(stderr, "gen-tables: lowp-list.h has %d functions, the kit %d\n", NF, kit_nfns1); return 1; }
  for (int f = 0; f < NF; f++)
    if (strcmp(NAMES[f], kit_fns1[f].name)) { fprintf(stderr, "gen-tables: %s against the kit's %s\n", NAMES[f], kit_fns1[f].name); return 1; }
#pragma omp parallel for schedule(dynamic)
  for (int f = 0; f < NF; f++)
    for (int m = 0; m < 4; m++)
      for (int x = 0; x < 256; x++) {
        T[f][0][m][x] = (unsigned char)kit_ref1(KIT_E5M2, kit_fns1[f].ref, x, RND[m]);
        /* kit_e4m3_saturate is a global: the two E4M3 results come from a
           helper that sets it on its own, under a lock */
        unsigned char nan, sat;
#pragma omp critical
        {
          kit_e4m3_saturate = 0;
          nan = (unsigned char)kit_ref1(KIT_E4M3, kit_fns1[f].ref, x, RND[m]);
          kit_e4m3_saturate = 1;
          sat = (unsigned char)kit_ref1(KIT_E4M3, kit_fns1[f].ref, x, RND[m]);
          kit_e4m3_saturate = 0;
        }
        T[f][1][m][x] = sat;
        if (nan != sat) {
          /* the only difference allowed: NaN in place of the largest value */
          if ((nan & 0x7f) != 0x7f || (sat & 0x7f) != 0x7e) {
            fprintf(stderr, "gen-tables: %s(0x%02x) in E4M3: 0x%02x, saturating 0x%02x\n", NAMES[f], x, nan, sat);
            exit(1);
          }
          OVF[f][m][x >> 3] |= (unsigned char)(1 << (x & 7));
        }
      }
  printf("/* lowp-tables.h: generated by gen-tables.c from MPFR, through the kit's\n"
         "   kit_ref1; do not edit. make lowp-tables regenerates it, and\n"
         "   make check checks that it is up to date.\n"
         "   LOWP_T[function][0: E5M2, 1: E4M3 saturating][mode: nearest, up, down,\n"
         "   zero][input]; LOWP_OVF[function][mode][input / 8], bit input %% 8: the E4M3\n"
         "   result overflowed away from zero (NaN unless saturating). */\n");
  printf("static const uint8_t LOWP_T[%d][2][4][256] = {\n", NF);
  for (int f = 0; f < NF; f++) {
    printf("/* %s */ {\n", NAMES[f]);
    for (int k = 0; k < 2; k++) {
      printf(" {\n");
      for (int m = 0; m < 4; m++) {
        printf("  {");
        for (int x = 0; x < 256; x++) printf("%s%d%s", x % 32 ? "" : "\n   ", T[f][k][m][x], x < 255 ? "," : "");
        printf("}%s\n", m < 3 ? "," : "");
      }
      printf(" }%s\n", k < 1 ? "," : "");
    }
    printf("}%s\n", f < NF - 1 ? "," : "");
  }
  printf("};\n");
  printf("static const uint8_t LOWP_OVF[%d][4][32] = {\n", NF);
  for (int f = 0; f < NF; f++) {
    printf("/* %s */ {", NAMES[f]);
    for (int m = 0; m < 4; m++) {
      printf("{");
      for (int i = 0; i < 32; i++) printf("%d%s", OVF[f][m][i], i < 31 ? "," : "");
      printf("}%s", m < 3 ? "," : "");
    }
    printf("}%s\n", f < NF - 1 ? "," : "");
  }
  printf("};\n");
  return 0;
}
