"""gen-tgamma.py -> ival/tgamma-table.h (2026-10-02): what ival_tgamma needs besides CORE-MATH's cr_tgamma.

Gamma is decreasing then increasing on (0, inf), with its minimum at x0 = 1.4616...; on each segment (-n-1, -n) of
the negatives it has one extremum x_n (a root of digamma), a minimum where Gamma > 0 (n odd) and a maximum where
Gamma < 0 (n even), and runs to +-inf at both poles. None of these points is a binary64 value, so each is written as
the two binary64 values around it, xlo < x < xhi, and its value rounded down and up. The table stops at the first
segment where every binary64 value has |Gamma| < 2^-1074 (the ones next to the poles included): there and beyond,
the endpoints' rounded values (+-0 and the least subnormal) already equal the extremum's, so no entry is needed.
mpmath at 400 bits; each root bracketed in its segment and refined, then checked to lie strictly between its two
neighbours."""
import math, mpmath as mp
mp.mp.prec = 400
TINY = mp.mpf(2) ** -1074

def rd(v):   # the largest binary64 value <= v (v an mpf), with +0 for 0 < v < 2^-1074
    f = float(v)
    if mp.mpf(f) > v: f = math.nextafter(f, -math.inf)
    return f
def ru(v):
    f = float(v)
    if mp.mpf(f) < v: f = math.nextafter(f, math.inf)
    return f
def around(x):   # the binary64 values just below and above x (x not a binary64 value)
    f = float(x)
    if mp.mpf(f) == x: raise SystemExit(f"{x} is a binary64 value")
    return (f, math.nextafter(f, math.inf)) if mp.mpf(f) < x else (math.nextafter(f, -math.inf), f)

def root(a, b):   # digamma's root in (a, b), by bisection to 400 bits (digamma is increasing on each segment)
    lo, hi = mp.mpf(a), mp.mpf(b)
    for _ in range(420):
        mid = (lo + hi) / 2
        if mp.digamma(mid) < 0: lo = mid
        else: hi = mid
    return (lo + hi) / 2

rows = []
x0 = root(1.4, 1.5)
x0lo, x0hi = around(x0)
g0 = mp.gamma(x0)
n = 0
while True:
    a, b = -n - 1, -n
    # the binary64 values next to the poles, inside the segment
    pa, pb = math.nextafter(float(a), 0.0), math.nextafter(float(b), -math.inf)
    big = max(abs(mp.gamma(mp.mpf(pa))), abs(mp.gamma(mp.mpf(pb))))
    if big < TINY: break
    eps = mp.mpf(2) ** -300
    xn = root(a + eps, b - eps)
    lo, hi = around(xn)
    assert a < lo < xn < hi < b
    g = mp.gamma(xn)
    assert (g > 0) == (n % 2 == 1), n
    rows.append((lo, hi, rd(g), ru(g)))
    n += 1
NT = len(rows)
out = ["/* tgamma-table.h: generated by gen-tgamma.py -- do not edit */",
       f"#define TG_X0LO {x0lo.hex()}   /* Gamma's minimum on the positives lies between these two */",
       f"#define TG_X0HI {x0hi.hex()}",
       f"#define TG_MIN_RD {rd(g0).hex()}   /* the minimum, {mp.nstr(g0, 20)}, rounded down */",
       f"#define TG_NT {NT}   /* segments (-n-1, -n) with an entry; from n = TG_NT on, every binary64 value has |Gamma| < 2^-1074 */",
       "/* per segment (-n-1, -n): the extremum lies strictly between xlo and xhi; its value rounded down, rounded up */",
       "static const double TG_EXT[TG_NT][4] = {" + ",\n  ".join("{%s, %s, %s, %s}" % tuple(v.hex() for v in r) for r in rows) + "};"]
open("ival/tgamma-table.h", "w").write("\n".join(out) + "\n")
print("x0 =", mp.nstr(x0, 25), "min", mp.nstr(g0, 25), "; NT =", NT, "; last row", rows[-1])
