/* gen-exceptions16: crnn-exceptions16.h, every binary16 and bfloat16 input
   at which a one-argument function's fast path (crnn-fast.h) with the
   format's rounding test (crnn-round16.h) can't decide the result, with the
   correctly rounded result from MPFR (crnn-ref.c, kit_ref1). All 2^16
   inputs of each function and format are tried (2026-10-01).
     make crnn-exceptions16 */
#include <fenv.h>
#include <stdio.h>
#include <stdlib.h>
#include "kit.h"
#include "crnn-fast.h"
#include "crnn-ref.h"
#include "crnn-round16.h"

static const kit_mpfr1 REF[CRNN_NFN1] = {crnn_mpfr_sigmoid, crnn_mpfr_silu, crnn_mpfr_gelu, crnn_mpfr_softplus, kit_mpfr_rsqrt};
static const kit_fmt KF[CRNN16_NFMT] = {KIT_B16, KIT_BF16};
static const char *const FN[CRNN16_NFMT] = {"f16", "bf16"};

int main(void)
{
  fesetenv(FE_DFL_ENV);
  printf("/* crnn-exceptions16.h: generated by nn/gen-exceptions16.c (make crnn-exceptions16); do not edit.\n"
         "   Every binary16 and bfloat16 input at which a fast path in crnn-fast.h, with the\n"
         "   format's rounding test (crnn-round16.h), can't decide the result, with the\n"
         "   correctly rounded result (MPFR), sorted by input bits. */\n#include <stddef.h>\n#include <stdint.h>\n");
  for (int fmt = 0; fmt < CRNN16_NFMT; fmt++)
    for (int f = 0; f < CRNN_NFN1; f++) {
      printf("static const uint16_t crnn_exc16_%s_%s[][2] = {", FN[fmt], crnn_fn1_name[f]);
      size_t n = 0;
      for (uint32_t u = 0; u < 65536; u++) {
        double x = crnn16_decode(fmt, (uint16_t)u), y;
        if (x != x || isinf(x) || x == 0 || (f == CRNN_RSQRT && x < 0)) continue;
        if (crnn16_round(fmt, crnn_fast(f, x), &y)) continue;
        uint16_t want = (uint16_t)kit_ref1(KF[fmt], REF[f], u, MPFR_RNDN);
        printf("%s{0x%04x, 0x%04x}", !n ? "\n  " : n % 6 ? ", " : ",\n  ", u, want);
        n++;
      }
      printf("%s};\n#define CRNN_EXC16_N_%s_%s %zu\n", n ? "\n" : "{0, 0}", FN[fmt], crnn_fn1_name[f], n);
      fprintf(stderr, "%-5s %-8s %zu inputs undecided by the fast path\n", FN[fmt], crnn_fn1_name[f], n);
    }
  printf("static const struct { const uint16_t (*t)[2]; size_t n; } crnn_exc16[2][5] = {\n");
  for (int fmt = 0; fmt < CRNN16_NFMT; fmt++) {
    printf("  {");
    for (int f = 0; f < CRNN_NFN1; f++) printf("%s{crnn_exc16_%s_%s, CRNN_EXC16_N_%s_%s}", f ? ", " : "", FN[fmt], crnn_fn1_name[f], FN[fmt], crnn_fn1_name[f]);
    printf("}%s\n", fmt ? "" : ",");
  }
  printf("};\n");
  return 0;
}
