/* gen-exceptions: crnn-exceptions.h, the table of every binary32 input at
   which a one-argument function's fast path (crnn-fast.h) can't decide
   the rounding, with the correctly rounded result from MPFR (crnn-ref.c,
   kit_ref1). Every one of the 2^32 inputs of each function is tried.
     make crnn-exceptions   (minutes on a few cores) */
#include <fenv.h>
#include <omp.h>
#include <stdio.h>
#include <stdlib.h>
#include "kit.h"
#include "crnn-fast.h"
#include "crnn-ref.h"

static const kit_mpfr1 REF[CRNN_NFN1] = {crnn_mpfr_sigmoid, crnn_mpfr_silu, crnn_mpfr_gelu, crnn_mpfr_softplus, kit_mpfr_rsqrt};

static int cmp32(const void *a, const void *b) { uint32_t x = *(const uint32_t *)a, y = *(const uint32_t *)b; return x < y ? -1 : x > y; }

int main(void)
{
  printf("/* crnn-exceptions.h: generated by nn/gen-exceptions.c (make crnn-exceptions); do not edit.\n"
         "   Every binary32 input at which a fast path in crnn-fast.h can't decide\n"
         "   the rounding, with the correctly rounded result (MPFR), sorted by input bits. */\n");
  for (int f = 0; f < CRNN_NFN1; f++) {
    size_t cap = 1 << 16, n = 0; uint32_t *hard = malloc(cap * 4);
#pragma omp parallel
    {
      fesetenv(FE_DFL_ENV);
      size_t lc = 1024, ln = 0; uint32_t *loc = malloc(lc * 4);
#pragma omp for schedule(dynamic, 1 << 16)
      for (int64_t i = 0; i < (int64_t)1 << 32; i++) {
        uint32_t u = (uint32_t)i; float x, y; memcpy(&x, &u, 4);
        if (crnn_special(f, x, &y)) continue;
        if (crnn_round32(crnn_fast(f, x), &y)) continue;
        if (ln == lc) loc = realloc(loc, (lc *= 2) * 4);
        loc[ln++] = u;
      }
#pragma omp critical
      {
        while (n + ln > cap) hard = realloc(hard, (cap *= 2) * 4);
        memcpy(hard + n, loc, ln * 4); n += ln;
      }
      free(loc);
    }
    qsort(hard, n, 4, cmp32);
    uint32_t *want = malloc((n ? n : 1) * 4);
#pragma omp parallel for schedule(dynamic, 1)
    for (size_t i = 0; i < n; i++) want[i] = (uint32_t)kit_ref1(KIT_B32, REF[f], hard[i], MPFR_RNDN);
    printf("static const uint32_t crnn_exc_%s[][2] = {", crnn_fn1_name[f]);
    for (size_t i = 0; i < n; i++) printf("%s{0x%08xu, 0x%08xu}", !i ? "\n  " : i % 4 ? ", " : ",\n  ", hard[i], want[i]);
    printf("%s};\n", n ? "\n" : "{0, 0}");
    printf("#define CRNN_EXC_N_%s %zu\n", crnn_fn1_name[f], n);
    fprintf(stderr, "%-8s %zu inputs undecided by the fast path\n", crnn_fn1_name[f], n);
    free(hard); free(want);
  }
  printf("static const struct { const uint32_t (*t)[2]; size_t n; } crnn_exc[] = {\n"
         "  {crnn_exc_sigmoid, CRNN_EXC_N_sigmoid}, {crnn_exc_silu, CRNN_EXC_N_silu}, {crnn_exc_gelu, CRNN_EXC_N_gelu},\n"
         "  {crnn_exc_softplus, CRNN_EXC_N_softplus}, {crnn_exc_rsqrt, CRNN_EXC_N_rsqrt}};\n");
  if (crnn_ref_long) fprintf(stderr, "note: %lu inputs needed more than 512 bits\n", crnn_ref_long);
  return 0;
}
